---
title: "Appex 10"
author: "Lucy D'Agostino McGowan"
output: github_document
date: '2022-03-23'
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(MatchIt)
library(broom)
library(smd)
#install.packages("smd")
```

```{r, message = FALSE, warning = FALSE}
customer_satisfaction <- read_csv("customer_satisfaction.csv")
```

```{r}
customer_satisfaction <- glm(
  satisfied_customer_service ~ gender + 
    education + married + n_kids + geographic_location + 
    previous_spend + new_customer + has_pets + former_customer_service, 
  data = customer_satisfaction, family = binomial) %>%
  augment(customer_satisfaction, type.predict = "response") %>%
  mutate(wt_ate = satisfied_customer_service / .fitted + 
           (1 - satisfied_customer_service) / (1 - .fitted),
         wt_ato = (1 - satisfied_customer_service) * .fitted + 
           satisfied_customer_service * (1 - .fitted))
```

```{r}
customer_satisfaction %>%
  summarize(
    across(c(gender, age, education, geographic_location, income, married, 
             n_kids, has_pets, former_customer_service, previous_spend,
             new_customer),
           list(
             unweighted = ~smd(.x, satisfied_customer_service)$estimate,
             ate.weighted = ~smd(.x, satisfied_customer_service, w = wt_ate)$estimate,
             ato.weighted = ~smd(.x, satisfied_customer_service, w = wt_ato)$estimate
           ))
  )
```

